console.log('Starting imports...');
import { initDatabase } from './database/database.js';
console.log('Database import ok');
import whatsappManager from './services/whatsappManager.js';
console.log('WhatsAppManager import ok');
import autoReplyService from './services/autoReplyService.js';
console.log('AutoReplyService import ok');
import accountRoutes from './routes/accountRoutes.js';
console.log('AccountRoutes import ok');
import messageRoutes from './routes/messageRoutes.js';
console.log('MessageRoutes import ok');
import mediaRoutes from './routes/mediaRoutes.js';
console.log('MediaRoutes import ok');
import configRoutes from './routes/configRoutes.js';
console.log('ConfigRoutes import ok');
import interactionRoutes from './routes/interactionRoutes.js';
console.log('InteractionRoutes import ok');
import proxyRoutes from './routes/proxyRoutes.js';
console.log('ProxyRoutes import ok');
console.log('ALL IMPORTS SUCCESSFUL');
